tg:
  bot:
    name: course_v1_bot
    token: ${BOT_TOKEN}

backend:
  url: ${API_URL}

logging:
  level:
    root: info
    com.anst.sd.telegram: DEBUG

spring:
  data:
    mongodb:
      uri: ${MONGO_URL}