server:
  port: 9097

tg:
  bot:
    name: course_v1_bot
    token: ${BOT_TOKEN}

backend:
  url: ${API_URL}

storage:
  user-state: userStageStorage
  user-name: userNameStorage
  access-token: accessTokenStorage
  refresh-token: refreshTokenStorage

security:
  ttl:
    access: 10m
    refresh: 168h

redis:
  url: ${REDIS_URL}
