server:
  port: 8084

tg:
  bot:
    name: course_v1_bot
    token: ${BOT_TOKEN}

backend:
  url: http://localhost:8080/api

logging:
  level:
    root: info
    com.anst.sd.telegram: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/tg?authSource=admin