tg:
  bot:
    name: course_v1_bot
    token: 6115795365:AAHM5HTbx9NAUjcSt_D6zU0R7UmkGIbZ8Ok

backend:
  url: http://localhost:8080/api

logging:
  level:
    root: info
    com.anst.sd.telegram: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/tg?authSource=admin