server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  servlet:
    context-path: /tg
  port: 8085

tg:
  bot:
    name: course_v1_bot
    token: ${BOT_TOKEN}

backend:
  url: ${API_URL}

logging:
  level:
    root: info
    com.anst.sd.telegram: DEBUG

spring:
  data:
    mongodb:
      uri: ${MONGO_URL_TG}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer

    bootstrap-servers: ${KAFKA_URL}