server:
  port: 8085
  servlet:
    context-path: /tg
tg:
  bot:
    name: course_v1_bot
    token: ${BOT_TOKEN}

logging:
  level:
    root: info
    com.anst.sd.telegram: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/tg?authSource=admin
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer

    bootstrap-servers: localhost:9092

service:
  api:
    api:
      url: https://localhost:8889 #url сервиса telegram-bot или заглушки. Нужно указать