name: deploy-dev

on:
  workflow_dispatch:
    branches:
      - 'dev'
#  push:
#    branches:
#      - 'dev'

jobs:
  # run-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'

  #     - name: Maven build jar
  #       run: mvn clean test

  build-push-image:
    runs-on: ubuntu-latest
    # needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven build jar
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: allokanic/tg-bot:latest

  send-info:
    needs: build-push-image
    uses: ./.github/workflows/template-telegram.yaml
    with:
      message: |
        Cluster: DEV 
        TELEGRAM status: redeploying started
    secrets: inherit

  run-on-cloud:
    runs-on: ubuntu-latest
    needs: send-info
    steps:
      - name: pull and rerun image
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_KEY_DEV }}"
          ssh -o StrictHostKeyChecking=no -tt root@${{ secrets.HOST_IP_DEV }} << EOT
            cd deploy
            docker-compose pull
            docker-compose up -d
            exit
          EOT

  success-notify:
    needs: run-on-cloud
    uses: ./.github/workflows/template-telegram.yaml
    with:
      message: |
        Cluster: DEV 
        TELEGRAM status: redeploying success
    secrets: inherit

  error-notify:
    needs: run-on-cloud
    if: ${{ failure() && needs.run-on-cloud.result == 'failure' }}
    uses: ./.github/workflows/template-telegram.yaml
    with:
      message: |
        Cluster: DEV 
        TELEGRAM status: redeploying error
    secrets: inherit
